const GRADES=["Pre-K","Kindergarten","Grade 1","Grade 2","Grade 3","Grade 4","Grade 5"];
const SUBJECTS=["Language Arts & Reading","Mathematics","Science","Social Studies","Art","Music","Social-Emotional Learning","Physical Education & Movement"];
const UNIT_THEMES={"Language Arts & Reading":["Foundations & Phonological Awareness","Letter-Sound Connections","Vocabulary & Meaning","Reading Fluency","Story Elements","Informational Text","Comprehension Strategies","Writing & Composition","Grammar & Language","Research & Communication"],"Mathematics":["Numbers & Counting","Place Value","Addition & Subtraction","Multiplication & Division","Fractions & Decimals","Measurement","Geometry","Patterns & Algebraic Thinking","Data & Graphing","Problem Solving"],"Science":["Scientific Thinking","Life Science","Earth & Space","Physical Science","Matter & Energy","Forces & Motion","Weather & Climate","Ecosystems","Engineering & Design","Science in Everyday Life"],"Social Studies":["Self & Community","Families & Communities","Maps & Geography","Civics","Government","History & Time","Culture & Perspectives","Economics","Community & Citizenship","Inquiry & Projects"],"Art":["Lines & Shapes","Color","Texture","Form & Space","Pattern","Drawing","Painting","Collage & Mixed Media","Art & Culture","Creative Projects"],"Music":["Sound & Listening","Beat & Rhythm","Tempo","Dynamics","Melody","Instruments","Movement & Music","Music & Culture","Creating Music","Performance & Reflection"],"Social-Emotional Learning":["Self-Awareness","Feelings & Body Signals","Communication","Relationships","Self-Advocacy","Problem Solving","Regulation & Breaks","Perspective Taking","Routines & Independence","Reflection & Growth"],"Physical Education & Movement":["Body Awareness","Balance","Locomotor Movement","Coordination","Strength & Endurance","Rhythm & Movement","Games & Rules","Safety","Healthy Habits","Personal Goals"]};
const STORAGE="nva_academy_progress_v1"; const state=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||"{}")}catch(e){return{}}}; const key=(g,s,u,l)=>[g,s,u,l].join("|"); const save=p=>localStorage.setItem(STORAGE,JSON.stringify(p));
function populate(){const g=document.getElementById("grade"),s=document.getElementById("subject");GRADES.forEach((x,i)=>g.add(new Option(x,i)));SUBJECTS.forEach((x,i)=>s.add(new Option(x,i)));g.onchange=fillUnits;s.onchange=fillUnits;document.getElementById("unit").onchange=fillLessons;fillUnits();}
function fillUnits(){const s=SUBJECTS[+document.getElementById("subject").value],u=document.getElementById("unit");u.innerHTML="";UNIT_THEMES[s].forEach((x,i)=>u.add(new Option("Unit "+(i+1)+": "+x,i)));fillLessons();}
function fillLessons(){const l=document.getElementById("lesson");l.innerHTML="";for(let i=1;i<=10;i++)l.add(new Option("Lesson "+i,i-1));}
function record(g,s,u,l){return{grade:GRADES[g],subject:SUBJECTS[s],unit:u+1,unitTitle:UNIT_THEMES[SUBJECTS[s]][u],lesson:l+1,title:"Lesson "+(l+1)+": "+UNIT_THEMES[SUBJECTS[s]][u],goal:"I can learn and demonstrate the lesson goal in a way that works for me.",vocab:["learn","practice","show"],teach:"Learn the key idea using the example, picture, read-aloud, demonstration, or teacher explanation. Pause whenever you need processing time.",practice:"Try the example with support. You may point, select, type, write, draw, use AAC, match, move, or demonstrate.",activity:"Complete the activity using the response method that works for you. Repeat, reduce choices, or take a movement break when needed.",support:"Visual directions • read-aloud • repetition • processing time • movement break • quiet reset • reduced choices • step-by-step directions",assessment:"Show what you know. Mastery can be demonstrated through speaking, pointing, selecting, writing, typing, drawing, AAC, matching, or demonstration unless the communication mode itself is the target."};}
function openLesson(){const g=+document.getElementById("grade").value,s=+document.getElementById("subject").value,u=+document.getElementById("unit").value,l=+document.getElementById("lesson").value,r=record(g,s,u,l),p=state(),k=key(g,s,u,l),v=document.getElementById("lessonView");v.classList.remove("hidden");v.innerHTML='<span class="pill">'+r.grade+' • '+r.subject+' • Unit '+r.unit+'</span><h2>'+r.title+'</h2><h3>Learning goal</h3><p>'+r.goal+'</p><h3>Vocabulary</h3><p>'+r.vocab.join(" • ")+'</p><h3>Learn</h3><p>'+r.teach+'</p><h3>Practice</h3><p>'+r.practice+'</p><h3>Activity</h3><p>'+r.activity+'</p><h3>Ways to respond</h3><p>'+r.assessment+'</p><h3>Supports</h3><p>'+r.support+'</p><div class="actions"><button class="primary" onclick="markComplete(\''+k+'\')">Mark demonstrated</button><button class="secondary" onclick="takeBreak()">Take a break</button></div><p id="status">'+(p[k]?"✓ Demonstrated":"Not started")+'</p>';window.scrollTo({top:v.offsetTop-80,behavior:"smooth"});}
function markComplete(k){const p=state();p[k]="Demonstrated";save(p);document.getElementById("status").textContent="✓ Demonstrated — progress saved on this device."}
function takeBreak(){alert("Break time: stretch, breathe, move, get water, or use a quiet space. Return when you are ready.")}
function showProgress(){const done=Object.keys(state()).length,total=7*8*10*10,v=document.getElementById("progressView");v.classList.remove("hidden");v.innerHTML='<h2>Academy progress</h2><p><strong>'+done+' of '+total+'</strong> lessons demonstrated.</p><p>Progress is saved on this device. Mastery stages: Not Started → Learning → Practicing → Demonstrated → Mastered.</p>';window.scrollTo({top:v.offsetTop-80,behavior:"smooth"});}
document.addEventListener("DOMContentLoaded",populate);