const KEY="nva_classroom_v1";const $=id=>document.getElementById(id);
let db=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"classes":[],"selected":null}')}catch(e){return{classes:[],selected:null}}})();
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const esc=x=>String(x??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function init(){
 ACADEMY.grades.forEach((x,i)=>$("studentGrade").add(new Option(x,i)));
 ACADEMY.subjects.forEach((x,i)=>$("subject").add(new Option(x,i)));
 $("subject").onchange=fillUnits;$("unit").onchange=fillLessons;fillUnits();
 $("createClass").onclick=createClass;$("addStudent").onclick=addStudent;$("assignClass").onclick=assignClass;
 $("exportClassroom").onclick=exportClassroom;$("importClassroom").onchange=importClassroom;render();
}
function fillUnits(){const s=ACADEMY.subjects[+$("subject").value],u=$("unit");u.innerHTML="";ACADEMY.units[s].forEach((x,i)=>u.add(new Option("Unit "+(i+1)+": "+x,i)));fillLessons()}
function fillLessons(){const l=$("lesson");l.innerHTML="";for(let i=0;i<10;i++)l.add(new Option("Lesson "+(i+1)+": "+ACADEMY.lessonSteps[i],i))}
function createClass(){const name=$("className").value.trim();if(!name)return alert("Enter a class name.");const c={id:"c_"+Date.now(),name,teacher:$("teacherName").value.trim(),members:[],assignments:[]};db.classes.push(c);db.selected=c.id;$("className").value="";$("teacherName").value="";save();render()}
function current(){return db.classes.find(c=>c.id===db.selected)}
function addStudent(){const c=current(),name=$("studentName").value.trim();if(!c)return;if(!name)return alert("Enter a student name or nickname.");const grade=+$("studentGrade").value;if(c.members.some(m=>m.name.toLowerCase()===name.toLowerCase()))return alert("That student is already in this class.");c.members.push({id:"m_"+Date.now(),name,grade,assignments:{}});$("studentName").value="";save();render()}
function assignClass(){const c=current();if(!c||!c.members.length)return alert("Add at least one student first.");const sub=+$("subject").value,u=+$("unit").value,l=+$("lesson").value;let count=0;c.members.forEach(m=>{const r=ACADEMY.make(m.grade,sub,u,l);if(!m.assignments[r.id]){m.assignments[r.id]={id:r.id,title:r.title,subject:r.subject,unit:r.unitTitle,status:"Assigned"};count++}});save();render();alert(count+" student assignment"+(count===1?"":"s")+" added.")}
function stats(m){const a=Object.values(m.assignments||{});return{total:a.length,done:a.filter(x=>x.status==="Demonstrated"||x.status==="Mastered").length,mastered:a.filter(x=>x.status==="Mastered").length}}
function render(){const box=$("classes");box.innerHTML=db.classes.length?db.classes.map(c=>{const total=c.members.reduce((n,m)=>n+stats(m).total,0),done=c.members.reduce((n,m)=>n+stats(m).done,0);return '<div class="card classcard"><h3>'+esc(c.name)+'</h3><p>'+esc(c.teacher||"Teacher/caregiver")+'</p><p>'+c.members.length+' student'+(c.members.length===1?"":"s")+'</p><div class="progress"><i style="width:'+Math.min(100,done/Math.max(1,total)*100)+'%"></i></div><p>'+done+' of '+total+' assigned lessons completed</p><button class="secondary" data-open="'+c.id+'">Open class</button></div>'}).join(""):'<p class="muted">No classes yet. Create your first class above.</p>';document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>{db.selected=b.dataset.open;save();render()});const c=current();$("workspace").classList.toggle("hidden",!c);if(c)renderWorkspace(c)}
function renderWorkspace(c){$("classTitle").textContent=c.name;$("classMeta").textContent=(c.teacher?c.teacher+" • ":"")+"Class members: "+c.members.length;
const members=$("members");members.innerHTML='<h3>Students & progress</h3>'+(c.members.length?c.members.map(m=>{const st=stats(m);return '<div class="member"><div><strong>'+esc(m.name)+'</strong><div class="small">'+esc(ACADEMY.grades[m.grade])+' • '+st.done+'/'+st.total+' completed • '+st.mastered+' mastered</div></div><button class="secondary small" data-remove="'+m.id+'">Remove</button></div>'}).join(""):'<p class="muted">No students in this class yet.</p>');document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{if(confirm("Remove this student from the class?")){c.members=c.members.filter(m=>m.id!==b.dataset.remove);save();render()}});document.querySelectorAll("[data-assignment-status]").forEach(x=>x.onchange=()=>{const [mid,id]=x.dataset.assignmentStatus.split("|");const m=c.members.find(m=>m.id===mid);if(m&&m.assignments[id])m.assignments[id].status=x.value;save();render()});
const all={};c.members.forEach(m=>Object.values(m.assignments||{}).forEach(a=>{if(!all[a.id])all[a.id]={...a,students:{}};all[a.id].students[m.id]=a.status}));
$("classAssignments").innerHTML='<h3>Class assignments</h3>'+(Object.values(all).length?'<table><thead><tr><th>Lesson</th><th>Student progress</th></tr></thead><tbody>'+Object.values(all).map(a=>{const rows=c.members.filter(m=>a.students[m.id]).map(m=>'<div><strong>'+esc(m.name)+'</strong> <select class="status" data-assignment-status="'+m.id+"|"+a.id+'"><option '+(a.students[m.id]==="Assigned"?"selected":"")+'>Assigned</option><option '+(a.students[m.id]==="Learning"?"selected":"")+'>Learning</option><option '+(a.students[m.id]==="Demonstrated"?"selected":"")+'>Demonstrated</option><option '+(a.students[m.id]==="Mastered"?"selected":"")+'>Mastered</option></select></div>').join("");return '<tr><td>'+esc(a.title)+'</td><td>'+rows+'</td></tr>'}).join("")+'</tbody></table>':'<p class="muted">No class assignments yet.</p>')}
function exportClassroom(){const blob=new Blob([JSON.stringify({academy:"Neurodivergent Voices Academy",version:1,exported:new Date().toISOString(),classroom:db},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="academy-classroom.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importClassroom(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const x=JSON.parse(reader.result);if(!x.classroom||!Array.isArray(x.classroom.classes))throw 0;db=x.classroom;save();render();alert("Classroom imported.")}catch(err){alert("That file could not be imported as an Academy classroom.")}};reader.readAsText(file)}
document.addEventListener("DOMContentLoaded",init);