const WEEK_1=[["Reading & Language Arts", "My Name", "I can recognize my name.", "🪪", "Which one says Maya?", ["Maya", "Max", "Mom"], "Maya", "Try looking for the name with the matching letters."], ["Mathematics", "Count 1–5", "I can count objects to 5.", "🍎", "How many apples? 🍎🍎🍎", ["2", "3", "5"], "3", "Count each apple one time."], ["Science", "My Body & Five Senses", "I can name a body part I use to see.", "👀", "Which body part helps me see?", ["Ears", "Eyes", "Feet"], "Eyes", "Think about the body part you use for looking."], ["Social Studies", "All About Me", "I can tell something about myself.", "🧒", "Which answer tells something about you?", ["My name", "A random number", "A weather report"], "My name", "Choose something that describes you."], ["Writing", "Lines & Shapes", "I can make lines and shapes.", "⭕", "Which shape has no corners?", ["Square", "Triangle", "Circle"], "Circle", "Think about a round shape."], ["Art", "Self-Portrait", "I can make a picture of myself.", "🎨", "A self-portrait is a picture of…", ["Myself", "A bus", "A tree"], "Myself", "A self-portrait shows the artist."], ["Music", "Loud & Quiet", "I can tell the difference between loud and quiet.", "🎵", "Which sound is quiet?", ["Whistle", "Whisper", "Drum crash"], "Whisper", "A whisper uses a soft voice."], ["Learning Skills", "My Visual Schedule", "I can follow a simple visual schedule.", "📅", "Snack → Story. What comes after snack?", ["Story", "Lunch", "Home"], "Story", "Look at the order of the pictures or words."], ["Communication", "Making a Choice", "I can make a choice.", "💬", "Which response shows a choice?", ["I don’t know", "Bananas, please.", "Go away."], "Bananas, please.", "A choice tells someone what you want or prefer."]];
const WEEK_2=[["Reading & Language Arts", "Feelings Words", "I can recognize a feeling word.", "😊", "Which is a feeling word?", ["Happy", "Table", "Blue"], "Happy", "Happy describes a feeling."], ["Mathematics", "Count Emotion Faces", "I can count objects to 5.", "🙂", "How many faces? 🙂🙂🙂🙂", ["3", "4", "5"], "4", "Count each face one time."], ["Science", "Body Signals", "I can notice a body signal.", "🍽️", "A growling tummy may mean…", ["Hungry", "Square", "Cold"], "Hungry", "Your body can send signals that tell you what it needs."], ["Social Studies", "Feelings & Friends", "I can choose a helpful response.", "🤝", "A friend looks sad. What could you do?", ["Laugh", "Offer help", "Walk away"], "Offer help", "Helping can be a kind response."], ["Writing", "Emotion Marks", "I can use marks or pictures to show a feeling.", "😀", "Which could show a happy feeling?", ["A big smile", "A blank page", "A stop sign"], "A big smile", "Faces and drawings can communicate feelings."], ["Art", "Feelings Colors", "I can draw a feeling face.", "🖍️", "What is the activity?", ["Draw a feeling face", "Count shoes", "Wash a cup"], "Draw a feeling face", "Art can help you communicate."], ["Music", "Fast & Slow", "I can tell fast and slow sounds apart.", "🎶", "Which is usually slower?", ["Lullaby", "Race music", "Fast drum beat"], "Lullaby", "Lullabies are often calm and slow."], ["Learning Skills", "Taking a Break", "I can choose a break when I need one.", "🧘", "When you feel overwhelmed, what can help?", ["Keep pushing", "Take a break", "Hide your feelings"], "Take a break", "A short break can help your body and brain reset."], ["Communication", "Asking for Help", "I can ask for help.", "🙋", "Which response asks for help?", ["No thanks.", "Help, please.", "Go away."], "Help, please.", "Those words clearly tell someone you need help."]];
const WEEK_3=[["Reading & Language Arts", "Family Words", "I can recognize a family word.", "👨‍👩‍👧", "Which word names a family member?", ["Sister", "Window", "Circle"], "Sister", "Sister is a word for a family member."], ["Mathematics", "Count Family Members", "I can count people in a group.", "👨‍👩‍👧‍👦", "How many people are at the table? 👨‍👩‍👧‍👦", ["2", "4", "6"], "4", "Count each person one time."], ["Science", "Growing & Changing", "I can describe one way people grow and change.", "📏", "Which is an example of growing?", ["Getting taller", "Turning into a chair", "Becoming a cloud"], "Getting taller", "People grow and change over time."], ["Social Studies", "Families Are Different", "I can understand that families can be different.", "🏠", "Which statement is true?", ["Every family is exactly the same.", "Families can look different.", "Families cannot change."], "Families can look different.", "Families can be different and still be families."], ["Writing", "Family Drawing", "I can draw or describe people important to me.", "✏️", "What could you draw or write about?", ["People important to me", "Only numbers", "A stoplight"], "People important to me", "You can use pictures, words, or another communication method."], ["Art", "My Family", "I can make a family collage.", "🖼️", "Which is an art activity?", ["Make a family collage", "Sort socks", "Measure rain"], "Make a family collage", "A collage combines pictures, shapes, or materials."], ["Music", "Family Songs", "I can participate in music in a way that works for me.", "🎤", "How can you participate in a family song?", ["Sing, hum, clap, or listen", "Leave the room", "Do math only"], "Sing, hum, clap, or listen", "Listening is also a valid way to participate."], ["Learning Skills", "Family Routines", "I can identify a familiar routine.", "🪥", "Which is a bedtime routine?", ["Brush teeth before bed", "A surprise every time", "A random event"], "Brush teeth before bed", "Routines are activities that happen in a familiar order."], ["Communication", "Talking About People", "I can use words, pictures, signs, or AAC to talk about people.", "🗣️", "What can you use to communicate about someone?", ["A picture or words", "Nothing", "Only running"], "A picture or words", "Many communication methods are valid."]];
const WEEK_4=[["Reading & Language Arts", "School Words", "I can recognize a school word.", "🏫", "Which word belongs at school?", ["Teacher", "Ocean", "Moon"], "Teacher", "A teacher is part of a school community."], ["Mathematics", "Shapes Around School", "I can identify basic shapes.", "🔺", "Which shape has 3 sides?", ["Circle", "Triangle", "Rectangle"], "Triangle", "A triangle has three sides."], ["Science", "Exploring Our Classroom", "I can explore safely and ask questions.", "🔎", "What is a safe way to explore?", ["Touch everything", "Look closely and ask questions", "Run around"], "Look closely and ask questions", "Safe exploration uses careful looking and questions."], ["Social Studies", "Community Helpers", "I can identify a community helper.", "🚒", "Which is a community helper?", ["Firefighter", "Artist", "Swimmer"], "Firefighter", "Firefighters help keep communities safe."], ["Writing", "My School", "I can draw or describe something at school.", "🏫", "What could you include in a picture about school?", ["A classroom", "A dinosaur only", "A random number"], "A classroom", "Think about a real place or person at school."], ["Art", "Classroom Collage", "I can create art from shapes or paper.", "✂️", "What could you use for a classroom collage?", ["Paper shapes", "Only food", "Only sounds"], "Paper shapes", "Paper shapes can be arranged into a collage."], ["Music", "Classroom Sounds", "I can notice sounds around me.", "📖", "Which is a classroom sound?", ["Pages turning", "Ocean waves only", "Thunder only"], "Pages turning", "Classrooms can have many everyday sounds."], ["Learning Skills", "Two-Step Directions", "I can follow a two-step direction.", "📝", "“Get your pencil and sit down.” What comes first?", ["Sit down", "Get my pencil", "Go home"], "Get my pencil", "Follow the steps in order."], ["Communication", "Asking for Help at School", "I can ask for help at school.", "🙋", "What can you say or communicate when you need help?", ["Help, please.", "Nothing", "Run away"], "Help, please.", "You can ask for help using speech, signs, pictures, or AAC."]];

const DATA = {
1:WEEK_1,2:WEEK_2,3:WEEK_3,4:WEEK_4
};
const storageKey="nva_prek_unit1_progress";
function getProgress(){try{return JSON.parse(localStorage.getItem(storageKey)||"{}")}catch(e){return {}}}
function saveProgress(p){localStorage.setItem(storageKey,JSON.stringify(p))}
function complete(week,lesson){const p=getProgress();p[`${week}-${lesson}`]=true;saveProgress(p)}
function isComplete(week,lesson){return !!getProgress()[`${week}-${lesson}`]}
function renderLesson(){
 const week=Number(document.body.dataset.week), lesson=Number(new URLSearchParams(location.search).get("lesson")||1);
 const item=DATA[week][lesson-1]; if(!item)return;
 document.getElementById("subject").textContent=item[0];
 document.getElementById("title").textContent=item[1];
 document.getElementById("objective").textContent=item[2];
 document.getElementById("visual").textContent=item[3];
 document.getElementById("question").textContent=item[4];
 const choices=document.getElementById("choices"); choices.innerHTML="";
 item[5].forEach((c,i)=>{const b=document.createElement("button");b.className="choice";b.textContent=c;b.onclick=()=>selectChoice(b,c,item[6],item[7]);choices.appendChild(b)});
 document.getElementById("weekLabel").textContent=`Week ${week} • Lesson ${lesson} of 9`;
 document.getElementById("back").href=`index.html`;
 document.getElementById("prev").href=lesson>1?`week-${week}.html?lesson=${lesson-1}`:`week-${week}.html`;
 document.getElementById("next").href=lesson<9?`week-${week}.html?lesson=${lesson+1}`:`index.html`;
 if(lesson===1)document.getElementById("prev").classList.add("disabled");
 if(lesson===9)document.getElementById("next").textContent="Back to Week";
 document.getElementById("complete").onclick=()=>{complete(week,lesson);document.getElementById("feedback").innerHTML='<span class="good">Lesson completed! Great work. ⭐</span>';updateProgress(week)};
 document.getElementById("breakBtn").onclick=()=>alert("Break time: take 3 slow breaths, stretch, get a drink of water, or use a quiet space. Come back when you are ready.");
}
function selectChoice(button,choice,answer,explain){
 document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));button.classList.add("selected");
 const f=document.getElementById("feedback");
 if(choice===answer){f.innerHTML=`<span class="good">Correct! ${explain}</span>`;button.setAttribute("aria-pressed","true");}
 else f.innerHTML=`<span class="bad">Good try. You can choose another answer. ${explain}</span>`;
}
function updateProgress(week){
 const done=DATA[week].filter((_,i)=>isComplete(week,i+1)).length;
 const el=document.getElementById("weekProgress"); if(el){el.style.width=(done/9*100)+"%";el.setAttribute("aria-valuenow",done)}
 const txt=document.getElementById("progressText");if(txt)txt.textContent=`${done} of 9 lessons completed`;
}
function renderDashboard(){
 const p=getProgress();let total=0;
 for(let w=1;w<=4;w++){let done=0;DATA[w].forEach((_,i)=>{if(p[`${w}-${i+1}`])done++});total+=done;const n=document.getElementById(`w${w}`);if(n)n.textContent=`${done}/9 complete`;const bar=document.getElementById(`bar${w}`);if(bar)bar.style.width=(done/9*100)+"%"}
 const totalEl=document.getElementById("totalProgress");if(totalEl)totalEl.style.width=(total/36*100)+"%";
 const totalText=document.getElementById("totalText");if(totalText)totalText.textContent=`${total} of 36 lessons completed`;
}
window.addEventListener("DOMContentLoaded",()=>{if(document.body.dataset.week) {renderLesson();updateProgress(Number(document.body.dataset.week))} else renderDashboard()});
